name: Simple GitHub Actions Workflow

on:
  push: 
    branches:
      - main

jobs:

  print-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print
        run: echo "Hello, World!"

  check-readme:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print README.md
        run: cat README.md
